# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07ef426fd46f352bf48eb4f72503507462d52a30410edfa6c80df282942533a8c10734291862e71f4b5aee783fcb34a82624810cf0897676a23f67b6ce528d08

test:
  secret_key_base: 904a7d5d3f068efa88cffd4fc51787874406fa9131d9daf89a8fc197a3b4b05fcd246a60deea2fac807ed3dd1d67a967a76e760f177938d985a38741f0c3c2ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
